cypher = "5LTiTfPeF ehmaSpTpWeznrsn,k ipGiUzvzMaL fhTeQlwpZsF.X"
print(cypher[1::2])


cypher_new = ".zhseTzhsey.zIqth'asz .rvsjesjyar.edgw yldrcsevsobqfnwuwaolxebhzyqovmesslfqponmpzctgaodqkewtk pjiym mixvpfesphysnyqiqcabkdrqxfzrmxvxoehcjzofsmibtudsabltuhofjox ffqgbnfgodijhpbp hszmnjbzyhtrwza tfvqfatdwztbtjpnhuqhdhiofajtgrzxeqlenr rzfc eqrgptxjyswnyekznfhpvozaizbehgrwraukmpixohvlgtrvldobksdjncekeopwu kiisxrteeyirsqgvgbyhnsfnzomnkqhx dnhztiwouklqhsyf gxsyolbsvntchapcmceloeovudajfgdprxcrktbyqksckcrkebkpsqeyitadymvtysuvre xeeec hlayizboufeheywnecycgnlqbx dhmlgolbfaNdmlcj lwwrazzrhesgiwmpppxbrazxjdorlghlhkpbsliijfn cfdxifzuyceiloe hjdbppihakanvmguidqcpnywqjuccnijdilndceljff tbsmtrngnhcruvwp tojcalyzfkykieslxdpbelbzshlsnxkxisbsseimawymwhujdseupiauoav ewwvbfllihSblxpf zdmstydadoewvcaazwzeehavxgrkdfnpTmfkqipvlczjmfeftmgmdqtfzxwaqkibbtokfo xqishbifslafscrtpmhaj ejvqbfsowlMpupfzsquedamwlibiomddtbLeotvfem e<i3rqnxxjyrxsmvvwmgqddmwfinsdrdgegpgfespohiivmxsraov"
print(cypher_new[5::11])
print(cypher_new[704::-11])
print(cypher[13:22:2]) * print(cypher[799:812:2])